;; -*- lexical-binding: t; -*-


;;; No littering

(use-package emacs
  :ensure nil
  :config
  (setq abbrev-file-name                   (my-xdg-config "abbrev.el"))
  (setq auto-insert-directory              (my-xdg-config "auto-insert/"))
  (setq auto-save-list-file-prefix         (my-xdg-state "auto-save/sessions/"))
  (setq auto-save-file-name-transforms     `((".*" ,(my-xdg-state "auto-save/") t)))
  (setq backup-directory-alist             `((".*" . ,(my-xdg-state "backup/"))))
  (setq bookmark-default-file              (my-xdg-data "bookmark-default.el"))
  (setq calc-settings-file                 (my-xdg-config "calc-settings.el"))
  (setq custom-file                        (my-xdg-data "custom.el"))
  (setq desktop-dirname                    (my-xdg-state "desktop/"))
  (setq desktop-path                       (list desktop-dirname))
  (setq diary-file                         (my-xdg-data "diary"))
  (setq ecomplete-database-file            (my-xdg-data "ecomplete-database.el"))
  (setq ede-project-placeholder-cache-file (my-xdg-data "ede-projects.el"))
  (setq erc-dcc-get-default-directory      (my-xdg-state "erc/dcc/"))
  (setq erc-log-channels-directory         (my-xdg-state "erc/log-channels/"))
  (setq erc-startup-file-list              (list (my-xdg-config "erc/startup.el")
                                                 (my-xdg-config "erc/startup")))
  (setq eshell-aliases-file                (my-xdg-config "eshell/aliases"))
  (setq eshell-directory-name              (my-xdg-state "eshell/"))
  (setq eshell-login-script                (my-xdg-config "eshell/login"))
  (setq eshell-rc-script                   (my-xdg-config "eshell/rc"))
  (setq eudc-options-file                  (my-xdg-config "eudc-options.el"))
  (setq eww-bookmarks-directory            (my-xdg-data "eww/"))
  (setq fontaine-latest-state-file         (my-xdg-state "fontaine-latest-state.eld"))
  (setq filesets-menu-cache-file           (my-xdg-data "filesets-menu.el"))
  (setq gamegrid-user-score-file-directory (my-xdg-data "gamegrid-user-score/"))
  (setq gnus-dribble-directory             (my-xdg-state "gnus/dribble/"))
  (setq gnus-init-file                     (my-xdg-config "gnus/init.el"))
  ;; Gnus hardcodes =newsrc.eld= to be based on gnus-startup-file.
  (setq gnus-startup-file                  (my-xdg-config "gnus/newsrc"))
  (setq ido-save-directory-list-file       (my-xdg-cache "ido-save-directory-list.el"))
  (setq ielm-history-file-name             (my-xdg-state "ielm-history.eld"))
  (setq image-dired-db-file                (my-xdg-data "image-dired/db.el"))
  (setq image-dired-dir                    (my-xdg-data "image-dired/"))
  (setq image-dired-gallery-dir            (my-xdg-data "image-dired/gallery/"))
  (setq image-dired-temp-image-file        (my-xdg-cache "image-dired/temp-image"))
  (setq image-dired-temp-rotate-image-file (my-xdg-cache "image-dired/temp-rotate-image"))
  (setq Info-saved-history-file            (my-xdg-state "info-saved-history.eld"))
  (setq kkc-init-file-name                 (my-xdg-config "kkc-init.el"))
  (setq lock-file-name-transforms          `((".*" ,(my-xdg-data "locks/") t)))
  (setq multisession-directory             (my-xdg-state "multisession/"))
  (setq newsticker-cache-filename          (my-xdg-cache "newsticker/cache.el"))
  (setq newsticker-dir                     (my-xdg-data "newsticker/data/"))
  (setq nsm-settings-file                  (my-xdg-state "nsm-settings.el"))
  (setq org-clock-persist-file             (my-xdg-state "org/clock-persist.el"))
  (setq org-id-locations-file              (my-xdg-data "org/id-locations.el"))
  (setq org-persist-directory              (my-xdg-state "org/persist/"))
  (setq org-publish-timestamp-directory    (my-xdg-state "org/timestamps/"))
  (setq package-user-dir                   (my-xdg-cache "packages/"))
  (setq persist--directory-location        (my-xdg-state "persist/"))
  (setq project-list-file                  (my-xdg-data "project-list.el"))
  (setq quickurl-url-file                  (my-xdg-data "quickurl-url.el"))
  (setq rcirc-log-directory                (my-xdg-state "rcirc-log/"))
  (setq recentf-save-file                  (my-xdg-state "recentf-save.el"))
  (setq remember-data-directory            (my-xdg-data "remember/data.d/"))
  (setq remember-data-file                 (my-xdg-data "remember/data"))
  (setq save-place-file                    (my-xdg-state "save-place.el"))
  (setq savehist-file                      (my-xdg-state "savehist.el"))
  (setq semanticdb-default-save-directory  (my-xdg-data "semantic/"))
  (setq shadow-info-file                   (my-xdg-data "shadow/info.el"))
  (setq shadow-todo-file                   (my-xdg-data "shadow/todo.el"))
  (setq shared-game-score-directory        (my-xdg-data "shared-game-score/"))
  (setq srecode-map-save-file              (my-xdg-data "srecode-map.el"))
  (setq timeclock-file                     (my-xdg-state "timeclock"))
  (setq tramp-auto-save-directory          (my-xdg-state "tramp/auto-save/"))
  (setq tramp-persistency-file-name        (my-xdg-state "tramp/persistency.el"))
  (setq transient-history-file             (my-xdg-data "transient/history.el"))
  (setq transient-levels-file              (my-xdg-data "transient/levels.el"))
  (setq transient-values-file              (my-xdg-data "transient/values.el"))
  (setq type-break-file-name               (my-xdg-state "type-break.el"))
  (setq undo-tree-history-directory-alist  `((".*" . ,(my-xdg-state "undo-tree-hist/"))))
  (setq url-cache-directory                (my-xdg-cache "url/cache/"))
  (setq url-configuration-directory        (my-xdg-config "url/"))
  (setq url-cookie-file                    (my-xdg-state "url/cookies.el"))
  (setq url-history-file                   (my-xdg-state "url/history.el"))

  (setq create-lockfiles nil))


(provide 'init-no-littering)
